### ISSUE TITLE
RAID creation problem

### ISSUE THREAD

**Issue by rpilot** [lenovo/powershell-redfish-lenovo#11]
Hello all,
Thanks for great examples of Lenovo Redfish implementation!
I'm trying to use existing functions from lenovo_utils.psm1 to create a new RAID volume using these simple commands:
```
$JsonHeader -> created by using the lenovo_utils create_session
$JsonBody = "{'Name': 'volumename', 'RAIDType': 'RAID5', 'CapacityBytes': -1}"
$target_URI = "https://Lenovo.XCC.IP/redfish/v1/Systems/1/Storage/RAID_Slot4/Volumes"
Invoke-WebRequest -Uri $target_URI -Headers $JsonHeader -Method Post -Body $JsonBody -ContentType 'application/json'
```

However I'm getting Bad Request error:
```
Invoke-WebRequest : The remote server returned an error: (400) Bad Request.
At line:1 char:25
+             $response = Invoke-WebRequest -Uri $target_URI -Headers $JsonHeader  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```
What can be wrong with the request? I'm working with ThinkSystem SR630 server and all firmware is dated around June-July 2020.

**Comment by renxulei** [comment]
@rpilot Hi, Vadym, could you try {'Name': 'volumename', 'RAIDType': 'RAID5'} if you want to use full capacity to create volume? and could you let me know the info below?
1. https://Lenovo.XCC.IP/redfish/v1/Systems/1/Storage/RAID_Slot4/Volumes
2. https://Lenovo.XCC.IP/redfish/v1/Systems/1/Storage/RAID_Slot4

if volume already existed under "Volumes", you need to delete them firstly then you can create new volume via Redfish API.
and also please ensure the Drives under RAID_Slot4 are same.

**Comment by rpilot** [comment]
@renxulei Hi, thanks for your advise! I have tried creating the volume with Python script and it worked. During this successful creation I printed the JsonBody to the screen. Then I deleted the volume and used the same $JsonBody = "{ 'RAIDType': 'RAID5', 'Name': 'volume1', 'Oem': {'Lenovo': {}}}" but this time with PowerShell and still getting error 400 BadRequest.
Seems to be some issue with Invoke-WebRequest and not related to lenovo_utils.psm1
I think this issue can be closed

**Comment by rpilot** [comment]
After playing a bit with the request I have found that the problem is in single quotes:
```
# Working request:
$JsonBody = '{"Name": "volumename","RAIDType": "RAID5"}'

# Bad request 400
$JsonBody = "{'Name': 'volumename','RAIDType': 'RAID5'}"
```

**Comment by renxulei** [comment]
@rpilot Really good to see the issue solved, thanks for the update!  I thought too much about the issue's root cause from the beginning.  :-)
