### ISSUE TITLE
Not working with powershell 7

### ISSUE THREAD

**Issue by deepak-ram-kumar** [lenovo/powershell-redfish-lenovo#116]
Not working with powershell 7.3.1

**Comment by panyy3** [comment]
Thanks for reporting this issue. We have reproduced it, and will have it fixed soon.

**Comment by deepak-ram-kumar** [comment]
Thanks, Much appreciated

**Comment by panyy3** [comment]
Hi, The issue has been fixed. Now we can support old powershell version and powershell 7. You pull the newest code from master and have a try. Let us know if you have any further problems.
