### ISSUE TITLE
Connection error when running the script against IMM system.

### ISSUE THREAD

**Issue by swahpy** [lenovo/powershell-redfish-lenovo#17]
Hello, following error happened when I run **lenovo_delete_bmc_user** command against Integrated Management Module system.
`Error message: Unable to connect to the remote server  
Please check arguments or server status.  
False`
Does the script work for IMM system?
Thanks very much.

**Comment by panyy3** [comment]
Hi Hywfred, The script can't work for IMM system.

**Comment by swahpy** [comment]
Hi, 
we have hundreds of Lenovo machines whose management system includes both XClarity and IMM. We plan to add new account for them. For XClarity Controller we could do it using this project. While for IMM ones, could you please provide some suggestions? Cause we have so many IMM systems, it's almost impossible to deploy the account manually. 
Besides, does IMM support redfish API?
Looking forward to your reply and thanks in advance.

**Comment by panyy3** [comment]
Hi Hywfred, IMM support redfish API. I will try to figure out whether it is possible to support user management on IMM using redfish API.

**Comment by swahpy** [comment]
Hi,
Thanks very much. If there're powershell scripts which support IMM, that would be great.

**Comment by panyy3** [comment]
Hi Hywfred, I am very sorry that I have to correct my answer on IMM redfish. Redfish is not supported on IMM. 
We suggest you to use OneCLI tool to do user management. You can get the tool from https://datacentersupport.lenovo.com
FYI.
Method to confirm whether redfish is supported or not: Access url https://bmcip/redfish in browser.
If "Access Error: 404 -- Not Found" is responsed, it means that redfish is not supported.
If "{"v1":"/redfish/v1/"}" is responsed, it means that redfish is supported.

**Comment by swahpy** [comment]
Hi panyy3,
Thanks for your sharing.
We'll try to use OneCli then. Still hope that we could implement remote management of IMM in this project. That would be great. Thanks again.
