### ISSUE TITLE
Redfish REST API shows drives as critical but they are healthy and online

### ISSUE THREAD

**Issue by maurice592** [lenovo/powershell-redfish-lenovo#47]
Hello,
the Lenovo/IBM support directed me to contact the developers on Github. By using the Redfish REST API all of the installed hard drives are shown as "Status":{"State":"Enabled","Health":"Critical"}. But the original state of health is "Normal". This original state is shown in XClarity Controller and confirmed by Lenovo support by checking the service data. My problem is that I monitor the server by a monitoring software using this REST API and the result is the monitoring software is alerting because the drives are critical. Which possibilities do I have to fix this issue? Is it possible to reset the Redfish REST API?

The REST API is used by HTTP GET: https://<IP_of_xclarity_controller>/redfish/v1/Systems/1/Storage/RAID_Slot4/Drives/Disk.0 (as example for the first hard drive)

**Comment by panyy3** [comment]
Have you tried to restart BMC?
If not, please try it first.
You can do it on webUI, go to "Home" Page --> "Quick Actions" --> "Power Action" --> "Restart Manager Controller"
Or you can use restart_bmc.psm1 script in this repository.
Check whether the issue has been fixed after BMC restart.

If not, confirm whether UEFI and BMC firmware is the latest ones, upgrade them to latest if necessary.

If the issue not fixed after firmware upgrade, please help to collect service data and share us the case number and FFDC filename.

**Comment by maurice592** [comment]
Hello,

I am sorry for the delay. But only today we had the time to doing some tests with the server. To restart the BMC we tested before I contacted you for sure. Today we do the following:


  *   Take the server offline with disconnecting power more than 20 minutes
  *   Checked for new firmware updates via Lenovo Xpress Packs
  *   Installed the newest XCC firmware (8.40, released 14 Jun 2022)

The issue further exists that the API shows all drives as critical. I have collected the service data now and downloaded them from XCC. But it is too big for the attachment. How can I send you this data?

Best regards,

i.A. Maurice Barbré
Leiter Support u. Monitoring
[Ein Bild, das Person, Mann, stehend, darstellend enthält.Automatisch generierte Beschreibung]  [Microsoft Certified: Azure Fundamentals] ***@***.*** ***@***.*** ***@***.***
Tel.: +49 5021 889988
Fax.: +49 5021 889980
***@***.******@***.***>


[Ein Bild, das Text, ClipArt enthält.Automatisch generierte Beschreibung]
epc GmbH
Kräher Weg 54
31582 Nienburg

Amtsgericht Walsrode, HRB 30780
Geschäftsführer: Alexander Eggers, Frederik Eggers



Diese E-Mail enthält vertrauliche und/oder rechtlich geschätzte Informationen. Wenn Sie nicht der richtige
Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und
vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet

**Comment by panyy3** [comment]
Hi maurice592, please upload the log via web page https://logupload.lenovo.com/?initTab=1
And tell us the log name here after logs have been uploaded.

**Comment by maurice592** [comment]
Hello,

I have uploaded the logs by logupload.leovono.com. The confirmation email is in attachments. Do you need any other information?

Best regards,

i.A. Maurice Barbré
Leiter Support u. Monitoring
[Ein Bild, das Person, Mann, stehend, darstellend enthält.Automatisch generierte Beschreibung]  [Microsoft Certified: Azure Fundamentals] ***@***.*** ***@***.*** ***@***.***
Tel.: +49 5021 889988
Fax.: +49 5021 889980
***@***.******@***.***>


[Ein Bild, das Text, ClipArt enthält.Automatisch generierte Beschreibung]
epc GmbH
Kräher Weg 54
31582 Nienburg

Amtsgericht Walsrode, HRB 30780
Geschäftsführer: Alexander Eggers, Frederik Eggers



Diese E-Mail enthält vertrauliche und/oder rechtlich geschätzte Informationen. Wenn Sie nicht der richtige
Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und
vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet

**Comment by panyy3** [comment]
Hi maurice592, Thanks for log uploading. I cannot see the attachment you mentioned. Could you please share the log file name or case number or serial number about the log you have uploaded? With those information, I can identify which one is the log you have uploaded.

**Comment by maurice592** [comment]
Hi,

This is the log file name: 7X02CTO1WW_S4AMB685_xcc_220701-201337.tzz
This is the serial number: S4AMB685

Kind regards,

i.A. Maurice Barbré
Leiter Support u. Monitoring
[Ein Bild, das Person, Mann, stehend, darstellend enthält.Automatisch generierte Beschreibung]  [Microsoft Certified: Azure Fundamentals] ***@***.*** ***@***.*** ***@***.***
Tel.: +49 5021 889988
Fax.: +49 5021 889980
***@***.******@***.***>


[Ein Bild, das Text, ClipArt enthält.Automatisch generierte Beschreibung]
epc GmbH
Kräher Weg 54
31582 Nienburg

Amtsgericht Walsrode, HRB 30780
Geschäftsführer: Alexander Eggers, Frederik Eggers



Diese E-Mail enthält vertrauliche und/oder rechtlich geschätzte Informationen. Wenn Sie nicht der richtige
Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und
vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet

**Comment by panyy3** [comment]
Thanks maurice592. The issue is under investigation. We will update you details when root cause is identified.

**Comment by panyy3** [comment]
Hi maurice592, 
It seems that this 8 x 2.5 BP was added recently at 07/01/2022,13:55:12. 
"59	07/01/2022,13:55:12	1	0	1	N/A	N/A	N/A	N/A	01GV280	Backplane	W4ZS89E00PC	LNVO	1	SC57A01986	Backplane(SN: W4ZS89E00PC) is added."
From FFDC log, this symptom was due to BP SEP auto-config process is failed (PSoC control/status register reading failed), 
then it cause all Drives status would not report normally by IPMI sensor. 
So that we would suggest you try to "replace a Backplane" (Lenovo Part Number is 01GV280) for this issue, and also need to make sure cable routing is correct. Thanks.

SR630 Backplane cable routing guide:
https://thinksystem.lenovofiles.com/help/index.jsp?topic=%2F7X01%2F8x25_cable_routing.html&cp=4_7_5_7_2

**Comment by maurice592** [comment]
Hi,

Are you sure we must replace the backplane? Is it part of Lenovo warranty?
The server works fine for us. Only the monitoring by using the XClarity API is not possible. The change we have done was that the 8x SSD configuration was replaced by a 4x SSD configuration. Since this change the API will show the four SSDs as failed.

An additional info: The server is a datacenter. We do not have access every time. For replacements for which the server has to be shutdown, we have to make an appointment with the customer working on it.

Thanks for your support and have a nice day!

i.A. Maurice Barbré
Leiter Support u. Monitoring
[Ein Bild, das Person, Mann, stehend, darstellend enthält.Automatisch generierte Beschreibung]  [Microsoft Certified: Azure Fundamentals] ***@***.*** ***@***.*** ***@***.***
Tel.: +49 5021 889988
Fax.: +49 5021 889980
***@***.******@***.***>


[Ein Bild, das Text, ClipArt enthält.Automatisch generierte Beschreibung]
epc GmbH
Kräher Weg 54
31582 Nienburg

Amtsgericht Walsrode, HRB 30780
Geschäftsführer: Alexander Eggers, Frederik Eggers



Diese E-Mail enthält vertrauliche und/oder rechtlich geschätzte Informationen. Wenn Sie nicht der richtige
Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und
vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet

**Comment by panyy3** [comment]
Hi maurice592,
Based on technical analysis, the most possible reason might be "backplane power cable issue” or "backplane hardware issue". This is why we suggested you try to "replace a Backplane" and make sure cable routing is correct.
As you have noticed that the API show the four SSDs as failed since the 8x SSD configuration was replaced by a 4x SSD configuration, suggest that backplane power cable routing checking should be performed before backplane replacement.

About Lenovo warranty, I am sorry I have no idea about this. Could you please go to lenovo support website to have official service support?
