### ISSUE TITLE
Unable to set trust certificates (self signed)

### ISSUE THREAD

**Issue by notzen** [lenovo/powershell-redfish-lenovo#53]
Hello,

I get a connection error about unable to create tsl tunnel,
there is no option to trust self signed certificates in the connection to the hosts.

**Comment by jixj5** [comment]
Hi notzen,
    We have tried to get a connection on several machines with self signed certificates, but we have not found the problem of TSL tunnel error.  I'm not sure if there's something wrong with your self signed certificate.
    And we are working on providing a option to trust self certificates.

**Comment by notzen** [comment]
Hi, 
Could you please provide an example of what you use to test the self signed certs ?
what command do you use and how the syntax of the cmdlet please?

**Comment by jixj5** [comment]
Hi,
This is a self-signed certificate on a server. But our script has ignored the certificate when to get a connection.
[download_cert_self_signed.zip](https://github.com/lenovo/powershell-redfish-lenovo/files/8629325/download_cert_self_signed.zip)

The command example:
import-module .\get_cpu_inventory.psm1
get_cpu_inventory -ip 1.1.1.1 -username USERID -password PASSW0RD

you can try to open a new powershell cmd window to excute the commands.
