### ISSUE TITLE
RAID1 + hot spare creation problem

### ISSUE THREAD

**Issue by pietropiz** [lenovo/powershell-redfish-lenovo#59]
Hello,
i'm trying to leverage the Redfish API to create a new raid volume.
All of our servers come with 3 disks and we want to create a RAID 1 with the third disk as hot spare.

If I try to use use a direct call to the API or the "lenovo_create_raid_volume.psm1" example, in both cases I get the following 500 error message:
```
The remote server returned an error: (500) Internal Server Error.
Message         : The request failed due to an internal service error.  The service is still operational.
Resolution      : Resubmit the request.  If the problem persists, consider resetting the service.
```

If i try to create a RAID 5 or a RAID1 after disabling one of the disks, all is working ok.
My sample code is:
`$JsonBody = '{"Name": "Volume1","RAIDType": "RAID1"}'`

Is it possible to create a RAID1 with a hot spare through the Redfish API?

Attached the details of
/redfish/v1/Systems/1/Storage/RAID_Slot7
/redfish/v1/Systems/1/Storage/RAID_Slot7/Volumes

[RAID_Slot7.json.txt](https://github.com/lenovo/powershell-redfish-lenovo/files/8747600/RAID_Slot7.json.txt)
[Volumes.json.txt](https://github.com/lenovo/powershell-redfish-lenovo/files/8747601/Volumes.json.txt)

**Comment by jixj5** [comment]
Hi,
Redfish API does not support the setting of hot spare currently. 
So it is not possible to create a RAID1 with a hot spare through the Redfish API currently.
